#!/bin/bash

xjc -p com.kambi.feeds.model.runningball unregister_match_response.xsd
xjc -p com.kambi.feeds.model.runningball unregister_match_request.xsd
xjc -p com.kambi.feeds.model.runningball unbook_match_response.xsd
xjc -p com.kambi.feeds.model.runningball unbook_match_request.xsd
xjc -p com.kambi.feeds.model.runningball timestamp_response.xsd
xjc -p com.kambi.feeds.model.runningball timestamp_request.xsd
xjc -p com.kambi.feeds.model.runningball systemmessage_list.xsd
xjc -p com.kambi.feeds.model.runningball server_keep_alive.xsd
xjc -p com.kambi.feeds.model.runningball resend_request.xsd
xjc -p com.kambi.feeds.model.runningball register_match_response.xsd
xjc -p com.kambi.feeds.model.runningball register_match_request.xsd
xjc -p com.kambi.feeds.model.runningball match_list_response.xsd
xjc -p com.kambi.feeds.model.runningball match_list_request.xsd
xjc -p com.kambi.feeds.model.runningball match_clock_response.xsd
xjc -p com.kambi.feeds.model.runningball match_clock_request.xsd
xjc -p com.kambi.feeds.model.runningball market_price_list.xsd
xjc -p com.kambi.feeds.model.runningball logout.xsd
xjc -p com.kambi.feeds.model.runningball login.xsd
xjc -p com.kambi.feeds.model.runningball get_registered_matches_response.xsd
xjc -p com.kambi.feeds.model.runningball get_registered_matches_request.xsd
xjc -p com.kambi.feeds.model.runningball game_condition_list.xsd
xjc -p com.kambi.feeds.model.runningball feedback_response.xsd
xjc -p com.kambi.feeds.model.runningball feedback_request.xsd
xjc -p com.kambi.feeds.model.runningball event_list.xsd
xjc -p com.kambi.feeds.model.runningball error_request.xsd
xjc -p com.kambi.feeds.model.runningball client_keep_alive.xsd
xjc -p com.kambi.feeds.model.runningball book_match_response.xsd
xjc -p com.kambi.feeds.model.runningball book_match_request.xsd
